# Configuration file for the application
# Please replace placeholder values with your actual keys and settings.

api_keys:
  google_maps: "YOUR_GOOGLE_MAPS_API_KEY_HERE" # Replace with your actual Google Maps API Key
  # Placeholder for Google Cloud/ADK if needed later for the deployed agent
  # google_cloud_project_id: "YOUR_PROJECT_ID"
  # google_cloud_agent_id: "YOUR_AGENT_ID"

# Example other configurations:
# default_location: "São Paulo, Brazil"
# max_event_results: 50
